### ISSUE TITLE
Error on .Rmd knit

### ISSUE THREAD

**Issue by AugustT** [dfalbel/speech-keras#2]
I'm having issues trying to replicate this analysis so i have come back to trying to re-knit this Rmd as a starting point.

First, the document is missing a library call to keras which causes it to fail. 

With that fixed I get an error

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: Incompatible shapes: [32,29] vs. [32,30]
```

This is caused by L313, but has its origins in L248.  While at this point you report 30 classes (2nd dimension of second vector), I only have 29. 

I believe the root of this is in L209 where you tell the one-hot you want it to have length `29L` though I don't really understand how this function (`tf$one_hot`) works. I have replaced `29L` with `length(unique(df$class_id))`. This fixes the discrepancy I found in L248, and I no longer get an error at L313. Can you confirm this fix makes sense, and that the `29L` is an error?

Happy to put in PR with these changes

**Comment by dfalbel** [comment]
@AugustT You are right and this is really a bug. 

You can see that I use `30L` here: https://github.com/dfalbel/speech-keras/blob/master/02-generator.R#L39

I would love a PR with the changes!
