### ISSUE TITLE
Unable to replicate results

### ISSUE THREAD

**Issue by AugustT** [dfalbel/speech-keras#4]
Running the Markdown document I am unable to replicate the success reported, instead my classifier is not better than chance.

This is a real head-scratcher. I am running the document exactly as here. When i get to run the `fit_generator` my accuracy stays at ~0.03-0.04. I have tried a fresh installation of keras and anaconda, I have double checked the `df` is correct, but I cannot work out why we get such different results using the same code.

I'm really lost on this one so any thoughts/suggestions much appreciated. Running on windows... in case that would make a difference?!

**Comment by dfalbel** [comment]
@AugustT I will rerun the code this week. It could be related to `tf` python version.

**Comment by dfalbel** [comment]
FWIW I re-runed the code today with tf-1.13.1 and got the same accuracy as before. Could be some problem when downloading the data?
